language: node_js
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
